export const NOTIFICATION_LOG_REPOSITORY = Symbol("NOTIFICATION_LOG_REPOSITORY");
export const NOTIFICATION_RATE_LIMITER = Symbol("NOTIFICATION_RATE_LIMITER");
export const NOTIFICATION_RATE_LIMITER_CONFIG = Symbol("NOTIFICATION_RATE_LIMITER_CONFIG");
export const NOTIFICATION_DEDUP_STORE = Symbol("NOTIFICATION_DEDUP_STORE");
export const NOTIFICATION_OBSERVERS = Symbol("NOTIFICATION_OBSERVERS");
export const NOTIFICATION_RETRY_CONFIG = Symbol("NOTIFICATION_RETRY_CONFIG");
export const USER_PREFERENCE_REPOSITORY = Symbol("USER_PREFERENCE_REPOSITORY");
